SELECT PROJECT.ID ,
       DATEDIFF('MONTH',PROJECT.START_DATE,PROJECT.FINISH_DATE) AS months
FROM PROJECT
WHERE DATEDIFF('MONTH',PROJECT.START_DATE,PROJECT.FINISH_DATE) = (
    SELECT MAX(DATEDIFF('MONTH',P.START_DATE,P.FINISH_DATE))
    FROM PROJECT P
    )