INSERT INTO WORKER(name, birthday, level, salary) VALUES
                                                      ('IGOR', '1977-12-24', 'Middle', 3000),
                                                      ('HANNA', '1989-04-13', 'Trainee', 800),
                                                      ('OLEKSANDR', '1985-09-30', 'Senior', 5000),
                                                      ('LARYSA', '1992-07-19', 'Junior', 1500),
                                                      ('NATASHA', '1990-02-14', 'Middle', 2800),
                                                      ('VOLODYMYR', '1983-11-05', 'Senior', 4500),
                                                      ('IVAN', '1995-03-21', 'Junior', 1700),
                                                      ('TARAS', '1997-08-23', 'Trainee', 900),
                                                      ('OLEH', '1988-06-10', 'Middle', 3200),
                                                      ('YULIA', '1993-12-12', 'Junior', 1600),
                                                      ('ANDRII', '1986-10-07', 'Senior', 5200);

INSERT INTO CLIENT (NAME) VALUES    ('ABC Corp'),
                                    ('MegaSoft'),
                                    ('Tech Innovations'),
                                    ('Global Solutions'),
                                    ('NextGen Enterprises');

INSERT INTO PROJECT( CLIENT_ID,START_DATE, FINISH_DATE) VALUES  (1, '2021-01-15', '2022-01-15'),
                                                                (2, '2020-03-10', '2022-03-10'),
                                                                (3, '2023-05-01', '2023-06-01'),
                                                                (4, '2021-07-20', '2023-07-20'),
                                                                (5, '2019-09-01', '2021-09-01'),
                                                                (1, '2022-08-01', '2023-08-01'),
                                                                (2, '2018-01-01', '2019-04-01'),
                                                                (3, '2022-11-15', '2023-02-15'),
                                                                (4, '2020-10-05', '2021-10-05'),
                                                                (5, '2017-06-01', '2018-06-01');
INSERT INTO PROJECT_WORKER (PROJECT_ID, WORKER_ID) VALUES  (1, 1),
                                                           (1, 2),
                                                           (2, 3),
                                                           (2, 4),
                                                           (3, 5),
                                                           (4, 6),
                                                           (5, 7),
                                                           (5, 8),
                                                           (6, 9),
                                                           (7, 10),
                                                           (8, 11),
                                                           (9, 1),
                                                           (10, 2),
                                                           (10, 3),
                                                           (10, 4);
